config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :chat_rooms, only: [:new, :create, :show, :index]
  root 'chat_rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  belongs_to :user

  has_many :messages, dependent: :destroy
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }

  after_create_commit { MessageBroadcastJob.perform_later(self) } ## broadcast message

  def timestamp
    created_at.strftime('%H:%M:%S %d/%m/%y')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable

  has_many :chat_rooms
  has_many :messages

  def display_name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @chat_rooms = ChatRoom.all

    @message = Message.new
  end

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render :new
    end
  end

  private

    def chat_room_params
      params.require(:chat_room).permit(:title)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_chat_room.html.erb
<% if @chat_room.present? && @chat_room.id == chat_room.id %>
  <li><%= chat_room.title %></li>
<% else %>
  <li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>
<% end %>

app/views/chat_rooms/index.html.erb
<% content_for :aside_left do %>
  <ul class="ascii">
    <li>Available chat rooms:
      <ul>
        <%= render @chat_rooms %>
      </ul>
    </li>
  </ul>
  
  <div><%= link_to 'New chat room', new_chat_room_path %></div>
<% end %>



<!-- <div class="ascii-table">
    <table>
        <tr>
            <td>Jill</td><td>Smith</td><td>50</td>
        </tr>
    </table>
</div>
<div class="ascii-table">
    <table>
        <tr>
            <td>Jill</td><td>Smith</td><td>50</td>
        </tr>
        <tr>
            <td>Eve</td><td>Jackson
              asdasd sad asd sad asd asd dasdölkk kk ok ok k kk k k k kpasl l
            </td><td>94</td>
        </tr>
    </table>
</div> -->
<!-- <div class="ascii-chat-room">
  <div class="ascii-chat-room-wrapper">
    <div class="ascii-chat-room-message-wrapper">
      <div class="ascii-chat-room-message-header">
        Jill @ 11:24:00 01/10/17
      </div>
      <div class="ascii-chat-room-message">
        Inga nazister på våra gator
      </div>
    </div>
  </div>
</div> -->

app/views/chat_rooms/new.html.erb
<% content_for :main do %>
<h2>Add chat room</h2>
<%= form_for @chat_room do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
  </div>

  <%= f.submit "ADD NEW ROOM!" %>
<% end %>
<% end %>

app/views/chat_rooms/show.html.erb
<% content_for :aside_left do %>
<ul class="ascii">
  <li>Available chat rooms:
    <ul>
      <%= render @chat_rooms %>
    </ul>
  </li>
</ul>
<div><%= link_to 'New chat room', new_chat_room_path %></div>
<% end %>


<% content_for :main do %>

<div class="messages" id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <h2><%= @chat_room.title %></h2>
  <span class="corner tl"></span>
  <span class="corner tr"></span>

  
  <%= render @chat_room.messages %>
</div>


<div class="new-message-form-wrapper">

  <span class="corner tl"></span>
  <span class="corner tr"></span>
  <span class="corner bl"></span>
  <span class="corner br"></span>


  <%= form_for @message, url: '#' do |f| %>
    <%= f.label :body, 'New message' %>
    <%= f.text_area :body %>

    <small>From 2 to 1000 characters</small>

    <%= f.submit "Post" %>
  <% end %>
</div>

<div class="exit-wrapper">
<%= link_to "Exit room", chat_rooms_path %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Media Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <header class="header">
      <span class="corner tl"></span>
      <span class="corner tr"></span>
      <span class="corner bl"></span>
      <span class="corner br"></span>

      <!-- <h1>MEDIA CHAT</h1> -->
<pre>

  ___  ___ ___________ _____  ___  _____  _   _   ___ _____
  |  \/  ||  ___|  _  \_   _|/ _ \/  __ \| | | | / _ \_   _|
  | .  . || |__ | | | | | | / /_\ \ /  \/| |_| |/ /_\ \| |
  | |\/| ||  __|| | | | | | |  _  | |    |  _  ||  _  || |
  | |  | || |___| |/ / _| |_| | | | \__/\| | | || | | || |
  \_|  |_/\____/|___/  \___/\_| |_/\____/\_| |_/\_| |_/\_/

</pre>


    </header>

    <aside class="aside aside-left">
      <%= yield :aside_left %>

      <% if current_user %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      <% end %>
    </aside>


    <article class="main">
      <span class="corner tl"></span>
      <span class="corner bl"></span>

      <%= yield :main %>
    </article>


    <footer class="footer">
      <span class="corner tl"></span>
      <span class="corner tr"></span>
      <span class="corner bl"></span>
      <span class="corner br"></span>

      <ul>
        <li>Anton Ledström</li>
        <li><%= mail_to "antonledstrom@gmail.com" %></li>
        <li>070 895 55 86</li>
        <li>Klubbacken 34</li>
        <li>Hägersten</li>
        <li>129 39</li>
      </ul>
    </footer>

  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <ul class="ascii">
    <li class="timestamp"><span class="small"><%= message.timestamp %></span></li>
    <li><span class="small"> <%= message.user.display_name %>:</span>
      <ul>
        <li><%= message.body %></li>
      </ul>
    </li>
  </ul>
</div>